export const CATEGORY_COLORS = [
	"emerald",
	"blue",
	"sky",
	"cyan",
	"teal",
	"orange",
	"amber",
	"violet",
	"pink",
	"fuchsia",
	"indigo",
	"slate",
	"zinc",
	"lime",
	"neutral",
	"gray",
	"purple",
	"yellow",
	"stone",
	"rose",
	"red",
] as const;

export type CategoryColor = (typeof CATEGORY_COLORS)[number];

export const CATEGORY_COLOR_MAP: Record<CategoryColor, string> = {
	emerald: "bg-emerald-600 text-white",
	blue: "bg-blue-600 text-white",
	sky: "bg-sky-500 text-white",
	cyan: "bg-cyan-600 text-white",
	teal: "bg-teal-600 text-white",
	orange: "bg-orange-500 text-white",
	amber: "bg-amber-500 text-white",
	violet: "bg-violet-600 text-white",
	pink: "bg-pink-600 text-white",
	fuchsia: "bg-fuchsia-500 text-white",
	indigo: "bg-indigo-600 text-white",
	slate: "bg-slate-700 text-white",
	zinc: "bg-zinc-600 text-white",
	lime: "bg-lime-500 text-white",
	neutral: "bg-neutral-600 text-white",
	gray: "bg-gray-600 text-white",
	purple: "bg-purple-600 text-white",
	yellow: "bg-yellow-400 text-stone-900",
	stone: "bg-stone-600 text-white",
	rose: "bg-rose-600 text-white",
	red: "bg-red-600 text-white",
};

export const DEFAULT_CATEGORIES = [
	{ name: "Groceries", color: "emerald" },
	{ name: "Dining Out", color: "orange" },
	{ name: "Cafe", color: "amber" },
	{ name: "Food Delivery", color: "rose" },
	{ name: "Drinks", color: "violet" },
	{ name: "Rent", color: "blue" },
	{ name: "Utilities", color: "sky" },
	{ name: "Health", color: "teal" },
	{ name: "Transport", color: "slate" },
	{ name: "Travel", color: "indigo" },
	{ name: "Tech", color: "neutral" },
	{ name: "Subscriptions", color: "purple" },
	{ name: "Education", color: "yellow" },
	{ name: "Misc", color: "gray" },
	{ name: "Fees", color: "red" },
	{ name: "Taxes", color: "red" },
	{ name: "Social", color: "fuchsia" },
	{ name: "Date", color: "pink" },
	{ name: "Household", color: "stone" },
	{ name: "Hobby", color: "rose" },
	{ name: "Gas", color: "cyan" },
	{ name: "Rideshare", color: "zinc" },
	{ name: "Gym", color: "lime" },
] as const;
