export const CATEGORY_COLORS = [
	"emerald",
	"blue",
	"sky",
	"cyan",
	"teal",
	"orange",
	"amber",
	"violet",
	"pink",
	"fuchsia",
	"indigo",
	"slate",
	"zinc",
	"lime",
	"neutral",
	"gray",
	"purple",
	"yellow",
	"stone",
	"rose",
	"red",
] as const;

export type CategoryColor = (typeof CATEGORY_COLORS)[number];

export const BASE_CURRENCY = "USD";

export const CATEGORY_COLOR_MAP: Record<CategoryColor, string> = {
	emerald: "bg-emerald-600 text-white",
	blue: "bg-blue-600 text-white",
	sky: "bg-sky-500 text-white",
	cyan: "bg-cyan-600 text-white",
	teal: "bg-teal-600 text-white",
	orange: "bg-orange-500 text-white",
	amber: "bg-amber-500 text-white",
	violet: "bg-violet-600 text-white",
	pink: "bg-pink-600 text-white",
	fuchsia: "bg-fuchsia-500 text-white",
	indigo: "bg-indigo-600 text-white",
	slate: "bg-slate-700 text-white",
	zinc: "bg-zinc-600 text-white",
	lime: "bg-lime-500 text-white",
	neutral: "bg-neutral-600 text-white",
	gray: "bg-gray-600 text-white",
	purple: "bg-purple-600 text-white",
	yellow: "bg-yellow-400 text-stone-900",
	stone: "bg-stone-600 text-white",
	rose: "bg-rose-600 text-white",
	red: "bg-red-600 text-white",
};

export const VIBRANT_CATEGORY_COLORS: Record<string, string> = {
	emerald: "hsl(160, 84%, 39%)",
	blue: "hsl(217, 91%, 60%)",
	sky: "hsl(190, 84%, 50%)",
	cyan: "hsl(190, 84%, 50%)",
	teal: "hsl(160, 84%, 39%)",
	orange: "hsl(25, 95%, 53%)",
	amber: "hsl(38, 92%, 50%)",
	violet: "hsl(263, 70%, 50%)",
	pink: "hsl(0, 84%, 60%)",
	fuchsia: "hsl(263, 70%, 50%)",
	indigo: "hsl(217, 91%, 60%)",
	lime: "hsl(160, 84%, 39%)",
	purple: "hsl(263, 70%, 50%)",
	yellow: "hsl(38, 92%, 50%)",
	rose: "hsl(0, 84%, 60%)",
	red: "hsl(0, 84%, 60%)",
	slate: "#64748b",
	zinc: "#71717a",
	stone: "#78716c",
	gray: "#6b7280",
	neutral: "#737373",
};

export const COLOR_TO_HEX: Record<string, string> = {
	emerald: "#059669",
	blue: "#2563eb",
	sky: "#0ea5e9",
	cyan: "#0891b2",
	teal: "#0d9488",
	orange: "#ea580c",
	amber: "#f59e0b",
	violet: "#7c3aed",
	pink: "#ec4899",
	fuchsia: "#c026d3",
	indigo: "#4f46e5",
	slate: "#64748b",
	zinc: "#71717a",
	lime: "#65a30d",
	neutral: "#737373",
	gray: "#6b7280",
	purple: "#9333ea",
	yellow: "#eab308",
	stone: "#78716c",
	rose: "#f43f5e",
	red: "#dc2626",
};

export const DEFAULT_CATEGORIES = [
	{ name: "Groceries", color: "emerald" },
	{ name: "Dining Out", color: "orange" },
	{ name: "Cafe", color: "amber" },
	{ name: "Food Delivery", color: "rose" },
	{ name: "Drinks", color: "violet" },
	{ name: "Rent", color: "blue" },
	{ name: "Utilities", color: "sky" },
	{ name: "Health", color: "teal" },
	{ name: "Transport", color: "slate" },
	{ name: "Travel", color: "indigo" },
	{ name: "Tech", color: "neutral" },
	{ name: "Subscriptions", color: "purple" },
	{ name: "Education", color: "yellow" },
	{ name: "Misc", color: "gray" },
	{ name: "Fees", color: "red" },
	{ name: "Taxes", color: "red" },
	{ name: "Social", color: "fuchsia" },
	{ name: "Date", color: "pink" },
	{ name: "Household", color: "stone" },
	{ name: "Hobby", color: "rose" },
	{ name: "Gas", color: "cyan" },
	{ name: "Rideshare", color: "zinc" },
	{ name: "Gym", color: "lime" },
] as const;

export const DEFAULT_PAGE_SIZE = 20;
