import {
	Book,
	Briefcase,
	Bus,
	Car,
	Clapperboard,
	Coffee,
	CreditCard,
	Dumbbell,
	Gamepad as GamepadIcon,
	GraduationCap,
	Heart,
	Home,
	Laptop,
	Martini,
	Music,
	PartyPopper,
	Plane,
	Receipt,
	ShoppingBag,
	ShoppingCart,
	Smartphone,
	Star,
	Train,
	Tv,
	Utensils,
	Wifi,
	Zap,
} from "lucide-react";
import type { ElementType } from "react";

export const CATEGORY_ICON_MAP: Record<string, ElementType> = {
	Groceries: ShoppingCart,
	"Dining Out": Utensils,
	Cafe: Coffee,
	"Food Delivery": ShoppingBag,
	Drinks: Martini,
	Rent: Home,
	Utilities: Zap,
	Health: Heart,
	Transport: Bus,
	Travel: Car,
	Tech: Laptop,
	Subscriptions: CreditCard,
	Education: GraduationCap,
	Misc: Receipt,
	Fees: Receipt,
	Taxes: Receipt,
	Social: PartyPopper,
	Date: Heart,
	Household: Home,
	Hobby: Star,
	Gas: Car,
	Rideshare: Car,
	Gym: Dumbbell,
	Work: Briefcase,
};

export const BRAND_ICON_MAP: Record<string, ElementType> = {
	uber: Car,
	lyft: Car,
	amazon: ShoppingBag,
	netflix: Tv,
	spotify: Music,
	apple: Smartphone,
	starbucks: Coffee,
	mcdonalds: Utensils,
	burger: Utensils,
	subway: Train, 
	airbnb: Home,
	hotel: Home,
	flight: Plane,
	airline: Plane,
	delta: Plane,
	united: Plane,
	american: Plane,
	shell: Car,
	exxon: Car,
	bp: Car,
	chevron: Car,
	texaco: Car,
	target: ShoppingCart,
	walmart: ShoppingCart,
	kroger: ShoppingCart,
	costco: ShoppingCart,
	whole: ShoppingCart,
	trader: ShoppingCart,
	safeway: ShoppingCart,
	publix: ShoppingCart,
	aldi: ShoppingCart,
	lidl: ShoppingCart,
	heb: ShoppingCart,
	wegmans: ShoppingCart,
	cinema: Clapperboard,
	movie: Clapperboard,
	theatre: Clapperboard,
	theater: Clapperboard,
	kindle: Book,
	audible: Book,
	steam: GamepadIcon,
	nintendo: Laptop,
	xbox: Laptop,
	playstation: Laptop,
	internet: Wifi,
	wifi: Wifi,
	comcast: Wifi,
	verizon: Wifi,
	att: Wifi,
	tmobile: Wifi,
};
